config/routes.rb
Rails.application.routes.draw do
    
  devise_for :users
  root 'tag#index'
  resources :tag do
    resources :notes, only: [:new, :create]
  end

end

app/models/note.rb
# == Schema Information
#
# Table name: notes
#
#  id         :integer          not null, primary key
#  title      :string
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  tag_id     :integer
#

class Note < ActiveRecord::Base

	validates :title, length: { in: 6..240 }

	belongs_to :user
	belongs_to :tag
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  slug       :string
#  user_id    :integer
#
# Indexes
#
#  index_tags_on_slug  (slug) UNIQUE
#

class Tag < ActiveRecord::Base
	before_create :small_words
	
	include AlgoliaSearch
	extend FriendlyId
	friendly_id :slug_candidates, use: :slugged
	
	algoliasearch do
		attribute :name, :id
	end

	def slug_candidates
		[
			:name,
			[:name, :id]
		]
	end

	validates_uniqueness_of :name, :message => "already present"
	validates :name, length: { in: 1..20 }
	has_many :notes 
	has_many :users, through: :notes

	

	def small_words
		self.name.downcase!
		self.name.gsub(/\s+/, "")
	end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  username               :string
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#  index_users_on_username              (username) UNIQUE
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_uniqueness_of :username, :message => "already taken" 

  include Gravtastic
  gravtastic
  
  has_many :notes 
  has_many :tags, through: :notes

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
	before_action :authenticate_user!
	before_action :find_tag
	before_action :check_notes, only: [:new, :create]
	
	def new
		@note = Note.new
	end

	def create
		@note = current_user.notes.new note_params
		@note.tag = @tag
		if @note.save
			redirect_to @tag , notice: 'Added the note!'
		else
			redirect_to @tag, notice: "Can't add this dude"
		end
	end

	def edit
		
	end

	private

	def find_tag
		@tag = Tag.friendly.find(params[:tag_id])
	end

	def note_params
		params.require(:note).permit(:title)
	end

	def check_notes
		#asdf
		if current_user.tags.include?(@tag )
			redirect_to @tag, notice: 'dude you already a note'
		end
	end

end

app/controllers/tag_controller.rb
class TagController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  def index
  end

  def show
  	@hit = Tag.friendly.find(params[:id])
  end

  def new
  	@tag = Tag.new
  end

  def create
  	@tag = Tag.new tag_params
  	if @tag.save
  		redirect_to root_path, notice: 'tag added'
  	else
  		redirect_to root_path, alert: 'something went wrong'
  	end
  end

  private
  def tag_params
  	params.require(:tag).permit(:name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def show
  	@hit = Tag.friendly.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MightyGarden3684</title>

   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


</head>
<body>
<div class="progress">
      <div class="indeterminate"></div>
  </div>
<%= yield %>
  <script type="text/javascript">
  var rumbleBannerBackgroundColor, rumbleBannerTextColor, rumbleBannerLinkColor, rumbleBannerPlacement;
  rumbleBannerBackgroundColor = "#161616";
  rumbleBannerTextColor = "#b0b0b0";
  rumbleBannerLinkColor = "#ffffff";
  rumbleBannerPlacement = "bottom"; // Optionally replace with "bottom".
</script>
<script src="https://d4nnn7wspfa3h.cloudfront.net/banner-2015.js" type="text/javascript"></script>
</body>
</html>

app/views/notes/new.html.erb
<div class="container">
<%= form_for([@tag,@note]) do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title , placeholder: 'minimum 6 chars', class: "materialize-textarea",length: 240, required: true%>
<% end %>

<div class= "center-align"style="padding-top: 140px;">

  <a class="waves-effect waves-teal btn-flat" href="/tag/<%= @tag.name %>"><%= @tag.name %></a>
</div>
</div>

app/views/tag/index.html.erb
<% content_for :title do %>Instant-search<% end %>

<div class="padding: 10px;">
<% if user_signed_in?%>
<%= link_to  current_user.username,destroy_user_session_path, :method=>'delete',
  class: "waves-effect waves-teal btn-flat right"
 %>
 <%= link_to  "Add Tag", new_tag_path,
  class: "waves-effect waves-teal btn-flat left"
 %>
<% else %>
<%= link_to "sign in" ,new_user_session_path,class: "waves-effect waves-teal btn-flat right"%>
<% end %>
</div>

<div class="container">

<div style=" padding-bottom: 90px;">
  
 <h1 class="center-align">
  Arbor-Knight</h1>
  <p class="center-align">one word Social Network!
  </div>
   

</div>

<div class="row">

<form class="col s12">
   <div class="row">
    <div class="input-field col s10 offset-s1">
      <div class="card-panel hoverable">
      <input placeholder="Placeholder" id="user_name" type="text" class="validate">
      <label for="user_name"><i class="material-icons">Hey lets get started!</i></label>

      <div id="hits" class="collection">

      </div>
      </div>
      
      
      
  </div>
  </div>
  </form>
 </div>
 





<script type="text/javascript">
  $(document).ready(function() {
    var index = new AlgoliaSearch('UFVW660MPZ', 'c8365a0f4e12774a0e5badfe27fb037c').initIndex('<%= Tag.index_name %>');
    var hitTemplate = '<div class="hit-instant-search">' +
      '<a class="collection-item" href="/tag/{{{name}}}">{{{_highlightResult.name.value}}}</a>'  +
    '</div>';
    var hitTemplateCompiled = Hogan.compile(hitTemplate);
    function search(v) {
      index.search(v, function(success, content) {
        if (!success) {
          console.log("Error: " + JSON.stringify(content));
          return;
        }
        $('#hits').html('');
        $('#stats').append('<div class="processing_time pull-right"> Processing Time:' + content.processingTimeMS + 'ms</div>');
        $('#stats').append('<div class="nb_hits">hits: ' + content.nbHits + '</div>');
        for (var i = 0; i < content.hits.length; ++i) {
          $('#hits').append(hitTemplateCompiled.render(content.hits[i]));
        }
      }, { hitsPerPage: 10 });
    }
    $('input#user_name').change(function() {
      search($(this).val());
    }).keyup(function(e) {
      if (e.which == 27) {
        $(this).val('').change();
        return;
      }
      search($(this).val());
    }).focus(function(){
      $(this).attr("placeholder", "");
    }).blur(function(){
      $(this).attr("placeholder", "Search");
    }).focus();
    $('.search-terms a').click(function(e) {
      $("input#user_name").val($(this).text()).change().focus();
    });
    search('');
  });
</script>

app/views/tag/new.html.erb
<div class="container">
<%= form_for Tag.new, url: tag_index_path , method: 'post' do |f| %>
	<%= f.label :name%>
	<%= f.text_field :name ,placeholder: 'minimum 2 chars', class: "materialize-textarea",length: 10, required: true%>
<% end %>
</div>

app/views/tag/show.html.erb
<div class="" style="padding: 10px;">
<% if user_signed_in?%>
<% if !current_user.tags.include?(@hit ) %>
<a class="waves-effect waves-teal btn-flat right" href="/tag/<%= @hit.name %>/notes/new">New Note</a>
<% end %>
<% end %>
<a class="waves-effect waves-teal btn-flat left" href="/">Take me Back</a>
</div>
<div class="container">
<div class="center-align">
	<h1><%= @hit.name %></h1>
	<p><%= @hit.notes.count %> notes</p>
</div>



<% @hit.notes.each do |note| %>
	<div class="card-panel hoverable">
	<div class="chip">
	<%= image_tag note.user.gravatar_url, class: "circle responsive-img" %>
  	<%= note.user.username %>
  </div>

	<i class="right"><%= local_time_ago note.created_at %></i>
	<p class="flow-text">
	<%= note.title %>
	</p>
     </div>    
<% end %>

app/views/welcome/index.html.erb
<% content_for :title do %>Instant-search<% end %>

<h1>Instant-search example</h1>

<div class="well">
  A <code>Google-like</code> instant-search based on <code>AlgoliaSearch JS Client</code> + <code>Hogan</code> example.
</div>
 <div class="row">
<form class="col s12">
   <div class="row">
    <div class="input-field col s12">
      <input placeholder="Placeholder" id="user_name" type="text" class="validate">
      <label for="user_name">First Name</label>
      <div id="hits" class="collection">
      </div>
</div>
  </div>
  </form>
 </div>   



<script type="text/javascript">
  $(document).ready(function() {
    var index = new AlgoliaSearch('AAHPH6RMMW', 'ca7cddacfe022b6d988443bce51483d4').initIndex('<%= Tag.index_name %>');
    var hitTemplate = '<div class="hit-instant-search">' +
      '<a class="collection-item" href="/show/{{{name}}}">{{{_highlightResult.name.value}}}</a>'  +
    '</div>';
    var hitTemplateCompiled = Hogan.compile(hitTemplate);
    function search(v) {
      index.search(v, function(success, content) {
        if (!success) {
          console.log("Error: " + JSON.stringify(content));
          return;
        }
        $('#hits').html('');
        $('#hits').append('<div class="processing_time pull-right">Processing time: ' + content.processingTimeMS + 'ms</div>');
        $('#hits').append('<div class="nb_hits">Nb hits: ' + content.nbHits + '</div>');
        for (var i = 0; i < content.hits.length; ++i) {
          $('#hits').append(hitTemplateCompiled.render(content.hits[i]));
        }
      }, { hitsPerPage: 20 });
    }
    $('input#user_name').change(function() {
      search($(this).val());
    }).keyup(function(e) {
      if (e.which == 27) {
        $(this).val('').change();
        return;
      }
      search($(this).val());
    }).focus(function(){
      $(this).attr("placeholder", "");
    }).blur(function(){
      $(this).attr("placeholder", "Search");
    }).focus();
    $('.search-terms a').click(function(e) {
      $("input#user_name").val($(this).text()).change().focus();
    });
    search('');
  });
</script>